# Generated by Django 3.0.5 on 2020-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='people',
            field=models.IntegerField(),
        ),
    ]
