# Generated by Django 3.0.5 on 2020-04-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200406_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imaga',
            new_name='image',
        ),
    ]
