# Generated by Django 3.0.5 on 2020-04-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categor_name',
            new_name='category_name',
        ),
    ]
